# Welcome to Jekyll!
#

# Site settings
title: AAC in the Cloud
description: Choices Give us a Voice, June 24-25, 2026
html_description: |
  Choices Give us a Voice<br/>
  June 24-25, 2026<br/>
  sponsored by OpenAAC
owner: OpenAAC # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@openaac.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aacconference.com" # the base hostname & protocol for your site
social:
  github: https://github.com/aac-in-the-cloud
  facebook-official: https://www.facebook.com/AACintheCloud/
  #email: /contact/
  #flickr:
  #instagram:
  youtube-square: https://presenters.aacconference.com/
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
